---
id: Scribe
name: Scribe
full: Scribe client library
description: Packaged version of the PHP Scribe client.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Scribe
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha2
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: Apache 2.0
  uri: http://www.horde.org/licenses/apache
dependencies:
  required:
    php: ^7
    composer:
      horde/thrift: '*'
